importar librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
from pathlib import Path
from sklearn.preprocessing import OneHotEncoder
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

c:\dev\Analisis_Datos_2026_2\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

obtener el dataset

In [2]:
# Download latest version
path = kagglehub.dataset_download("gandpablo/cars-prices-for-machine-learning")

print("Path to dataset files:", r"C:\dev\Analisis_Datos_2026_2")

Path to dataset files: C:\dev\Analisis_Datos_2026_2

mostrar el dataset

In [3]:
archivos = list(Path(path).rglob("*"))
print("Archivos encontrados:")
for archivo in archivos:
    if archivo.is_file():
        print(archivo.name)

archivo_csv = next(archivo for archivo in archivos if archivo.suffix.lower() == ".csv")
df = pd.read_csv(archivo_csv)

display(df.head())

Archivos encontrados:
Cars_Data_6k.csv

,Unnamed: 0,Brand,Name,Sticker,Year,KM,Fuel,CV,Transmission,One_owner,...,Weight,Trunk,Tank,Vmax,0to100,Consumption,Emissions,Keys_num,Extras_num,Price
0,0,Opel,Opel Corsa,C,2022.0,47707.0,Diésel,102.0,MANUAL,True,...,1165.0,NaN,-,188.0,10.2,4.1,107.0,1.0,5.0,15700.0
1,1,Peugeot,Peugeot Rifter,C,2019.0,57194.0,Diésel,130.0,AUTO,True,...,1430.0,1355.0,-,179.0,4.3,114.0,NaN,2.0,5.0,24900.0
2,2,Renault,Renault Kadjar,C,2017.0,66428.0,Diésel,110.0,MANUAL,False,...,1380.0,1478.0,-,182.0,11.9,3.8,99.0,2.0,5.0,17800.0
3,3,Dacia,Dacia Sandero,C,2016.0,48430.0,Gasolina,75.0,MANUAL,True,...,941.0,1200.0,-,162.0,14.5,5.8,130.0,2.0,3.0,9300.0
4,4,Nissan,Nissan QASHQAI,C,2020.0,72209.0,Gasolina,160.0,AUTO,False,...,1315.0,1598.0,-,198.0,9.9,6.9,156.0,2.0,5.0,21500.0

dividir el conjunto de datos X - y

In [4]:
# Eliminar filas y columnas completamente vacías
df = df.dropna(axis=0, how="all").dropna(axis=1, how="all")

# Eliminar columna de índice original
df = df.drop(columns=["Unnamed: 0"], errors="ignore")

# Eliminar filas con valores nulos
df = df.dropna().copy()

# Separar primero la variable objetivo
y = df["Transmission"].copy()
X = df.drop(columns=["Transmission"]).copy()

# Convertir variables booleanas de X a 0 y 1
columnas_booleanas = X.select_dtypes(include="bool").columns
X[columnas_booleanas] = X[columnas_booleanas].astype(int)

# Convertir solamente las variables categóricas de X
columnas_categoricas = X.select_dtypes(
    include=["object", "category"]
).columns

X = pd.get_dummies(
    X,
    columns=columnas_categoricas,
    dtype=int
)

display(X.head())
print("Dimensiones de X:", X.shape)
print("Dimensiones de y:", y.shape)
print("Clases:", y.unique())

C:\Users\marti\AppData\Local\Temp\ipykernel_16652\2186939519.py:19: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_categoricas = X.select_dtypes(

,Year,KM,CV,Length,Width,Height,Weight,Trunk,Vmax,0to100,...,Location_Navarra,Location_Oviedo,Location_Pontevedra,Location_Santander,Location_Sevilla,Location_Toledo,Location_Valencia,Location_Vizcaya,Location_Zaragoza,Tank_-
2,2017.0,66428.0,110.0,4.45,1.84,1.61,1380.0,1478.0,182.0,11.9,...,0,0,0,0,0,0,0,0,0,1
3,2016.0,48430.0,75.0,4.06,1.73,1.52,941.0,1200.0,162.0,14.5,...,0,0,0,0,0,0,0,0,0,1
4,2020.0,72209.0,160.0,4.39,1.81,1.59,1315.0,1598.0,198.0,9.9,...,0,0,0,0,0,0,0,0,0,1
5,2018.0,123979.0,150.0,4.36,1.82,1.53,1575.0,1355.0,207.0,9.3,...,0,0,0,0,0,0,0,0,0,1
6,2018.0,125737.0,110.0,4.14,1.76,1.52,1255.0,1155.0,175.0,11.3,...,0,0,0,0,0,0,0,0,0,1

Dimensiones de X: (3416, 264)
Dimensiones de y: (3416,)
Clases: <StringArray>
['MANUAL', 'AUTO']
Length: 2, dtype: str

particionar

In [5]:
#particionar X y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [ ]:
modelo = svm.SVC(kernel='linear')
modelo = modelo.fit(X_train, y_train)
print(modelo)

In [ ]:
y_pred = modelo.predict(X_test)
print(classification_report(y_test, y_pred))